### PR TITLE
added once and removeListener cals to prototype

### PR DESCRIPTION
**Pull request by mattiLeBlanc**
Hi,
I need the removeListener() and the once() calls from the eventEmitter so I have added them to your project.
Would you do a merge?

Cheers,

Mattijs

### CODE REVIEW

**Comment by raix** [comment]
Thanks @mattiLeBlanc

**Comment by mattiLeBlanc** [comment]
Hi Morten,

You probably need up the version number in the package.js, otherwise meteor
update will not pick it up.
I forgot to do it myself in the fork.
Sorry for that.

Cheers,

Mattijs

**Comment by mattiLeBlanc** [comment]
Hi,

Can you tell me what the difference is between the capabilities
in raix:eventddp and raix:eventEmitter?
I use eventDDP now to send events from server to client and possibly the
other way around.

For a concrete example: I have a meteor.call from the client to the server
which does and insert and then starts to send emails. Just before the email
send which is a sync request, I emit an event to the client so that the
dialog can close.
When the meteor.call reaches it callback it will show a toast.
It works really well, but now I am opening to many events. So hence me
adding the remove listener.
However, I was wondering if the eventEmitter package can do the same as the
DDP package since this one already has all the functions.
I think I tried the package but I am correct I couldnt set up on the server
to emit event from server to client.

Cheers

Mattijs

**Comment by mattiLeBlanc** [comment]
yep, i can confirm that eventEmitter package does not communicate from
server to client. I also cant emit with eventDDP onserver and listen with
eventEmitter on client (probably two different techniques).
When can have the meteor package updated so that I can do a meteor update?

**Comment by mattiLeBlanc** [comment]
Sorry for spamming you :)
I cloned my for into the packages folder and updated the package version
and added it to Meteor so that I can use it (was having to many listeners
attached).

Anyway, I noticed that the 'once' handler did not work. It is using the one
from the EventEmitter package so probably that one doesnt work either.
I didn't unbind it, so I can the Memory leak warning after 10 executions.

Hope the feedback is helpful, I dont have time to look into it in detail
now, so if it is a walk in the park for you, that would be appreciated.

cheers

**Pull request merged**
